In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("Zadanie_1.csv", sep=';')

df

x1    x2    x3    x4    x5    x6    x7    x8    x9   x10   x11    x12  \
0   36.0  27.0  71.0   8.1  3.34  11.4  81.5  3243   8.8  42.6  11.7   21.0   
1   35.0  23.0  72.0  11.1  3.14  11.0  78.8  4281   3.6  50.7  14.4    8.0   
2   44.0  29.0  74.0  10.4  3.21   9.8  81.6  4260   0.8  39.4   NaN    6.0   
3   47.0  45.0  79.0   6.5  3.41  11.1  77.5  3125  27.1  50.2  20.6   18.0   
4   43.0  35.0  77.0   7.6  3.44   9.6  84.6  6441  24.4  43.7  14.3   43.0   
5   53.0  45.0  80.0   7.7  3.45  10.2  66.8  3325  38.5  43.1  25.5   30.0   
6   43.0  30.0  74.0  10.9  3.23  12.1  83.9  4679   3.5  49.2  11.3   21.0   
7   45.0  30.0  73.0   9.3  3.29  10.6  86.0  2140   5.3  40.4  10.5    6.0   
8   36.0  24.0  70.0   9.0  3.31  10.5  83.2  6582   8.1  42.5  12.6   18.0   
9   36.0  27.0  72.0   9.5  3.36  10.7  79.3  4213   6.7  41.0  13.2   12.0   
10  52.0  42.0  79.0   7.7  3.39   9.6  69.2  2302  22.2  41.3  24.2   18.0   
11  33.0  26.0  76.0   8.6  3.20  10.9  83.4  6122  16.3  44.9  10.7   88.0   
12  40.0  34.0  77.0   9.2  3.21  10.2  77.0  4101  13.0  45.7  15.1   26.0   
13  35.0  28.0  71.0   8.8  3.29  11.1  86.3  3042  14.7  44.6  11.4   31.0   
14  37.0  31.0  75.0   8.0  3.26  11.9  78.4  4259  13.1  49.6  13.9   23.0   
15  35.0  46.0  85.0   7.1  3.22  11.8  79.9  1441  14.8  51.2  16.1    1.0   
16  36.0  30.0  75.0   7.5  3.35  11.4  81.9  4029  12.4  44.0  12.0    6.0   
17  15.0  30.0  73.0   8.2  3.15  12.2  84.2  4824   4.7  53.1  12.7   17.0   
18  31.0  27.0  74.0   7.2  3.44  10.8  87.0  4834  15.8  43.5  13.6   52.0   
19   NaN  24.0  72.0   6.5  3.53  10.8  79.5  3694  13.1  33.8  12.4   11.0   
20  31.0  45.0  85.0   7.3  3.22  11.4  80.7  1844  11.5  48.1  18.5    1.0   
21  31.0  24.0  72.0   9.0  3.37  10.9  82.8  3226   5.1  45.2  12.3    5.0   
22  42.0  40.0  77.0   6.1  3.45  10.4  71.8  2269  22.7  41.4  19.5    8.0   
23  43.0  27.0  72.0   9.0  3.25  11.5  87.1  2909   7.2  51.6   9.5    7.0   
24  46.0  55.0  84.0   5.6  3.35  11.4  79.7  2647  21.0  46.9  17.9    6.0   
25  39.0   NaN  76.0   8.7  3.23  11.4  78.6  4412  15.6  46.6  13.2   13.0   
26  35.0  31.0  81.0   9.2  3.10  12.0  78.3  3262  12.6  48.6  13.9    7.0   
27   NaN  32.0  74.0  10.1  3.38   9.5  79.2  3214   2.9  43.7  12.0   11.0   
28  11.0  53.0  68.0   9.2  2.99  12.1  90.6  4700   7.8  48.9  12.3  648.0   
29  30.0  35.0  71.0   8.3  3.37   9.9  77.4  4474  13.1  42.6  17.7   38.0   
30  50.0  42.0  82.0   7.3  3.49  10.4  72.5  3497  36.7  43.3  26.4   15.0   
31  60.0  67.0  82.0  10.0  2.98  11.5  88.6  4657  13.6  47.3  22.4    NaN   
32   NaN   NaN  69.0   8.8  3.26  11.1   NaN  2934   5.8  44.0   9.4   33.0   
33  25.0  12.0  73.0   9.2  3.28  12.1  83.1  2095   2.0  51.9   9.8   20.0   
34  45.0  40.0  80.0   8.3  3.32  10.1  70.3  2682  21.0  46.1  24.1   17.0   
35  46.0  30.0   NaN  10.2  3.16  11.3  83.2  3327   NaN  45.3  12.2    4.0   
36  54.0  54.0  81.0   7.4  3.36   9.7  72.8  3172  31.4  45.5  24.2    NaN   
37  42.0  33.0  77.0   9.7  3.30  10.7  83.5  7462  11.3  48.7  12.4   41.0   
38  42.0  32.0  76.0   9.1  3.32  10.5  87.5  6092  17.5  45.3  13.2   29.0   
39  36.0  29.0  72.0   9.5  3.32  10.6  77.6  3437   8.1  45.5  13.8   45.0   
40  37.0  38.0  67.0  11.3  2.99  12.0  81.5  3387   3.6  50.3  13.5   56.0   
41  42.0  29.0  72.0  10.7  3.19  10.1  79.5  3508   2.2  38.3  15.7    6.0   
42  41.0  33.0  77.0  11.2  3.80   9.6  79.9  4843   2.7  38.6  14.1   11.0   
43  44.0  39.0  78.0   8.2  3.32  11.0  79.9  3768  28.6  49.5  17.5   12.0   
44  32.0  25.0  72.0  10.9  3.21   NaN  82.5  4355   5.0  46.4  10.8    7.0   
45  34.0  32.0  79.0   9.3  3.23   9.7  76.8  5160  17.2  45.1  15.3   31.0   
46  10.0  55.0  70.0   7.3  3.11  12.1  88.9  3033   5.9  51.0  14.0  144.0   
47  18.0  48.0  63.0   9.2  2.92  12.2  87.7  4253  13.7  51.2  12.0  311.0   
48  13.0  49.0  68.0   7.0  3.36  12.2  90.7  2702   3.0  51.9   9.7  105.0   
49  35.0  40.0  64.0   9.6  3.20  12.2  82.5  3626   5.7

In [3]:
df.to_numpy().shape

(60, 16)

In [4]:
data =  np.genfromtxt("Zadanie_1.csv", delimiter=';')
data

array([[         nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan],
       [3.600000e+01, 2.700000e+01, 7.100000e+01, 8.100000e+00,
        3.340000e+00, 1.140000e+01, 8.150000e+01, 3.243000e+03,
        8.800000e+00, 4.260000e+01, 1.170000e+01, 2.100000e+01,
                 nan, 5.900000e+01, 5.900000e+01, 9.218700e+02],
       [3.500000e+01, 2.300000e+01, 7.200000e+01, 1.110000e+01,
        3.140000e+00, 1.100000e+01, 7.880000e+01, 4.281000e+03,
        3.600000e+00, 5.070000e+01, 1.440000e+01, 8.000000e+00,
        1.000000e+01, 3.900000e+01, 5.700000e+01, 9.978750e+02],
       [4.400000e+01, 2.900000e+01, 7.400000e+01, 1.040000e+01,
        3.210000e+00, 9.800000e+00, 8.160000e+01, 4.260000e+03,
        8.000000e-01, 3.940000e+01,          nan, 6.000000e+00,
        6.000000e+00, 3.300000e+01, 5

In [5]:
#Zadanie 1
np.count_nonzero(data)

976

In [6]:
#Zadanie 1b
np.shape(data)

(61, 16)

In [7]:
#Zadanie 1c
np.mean(data)

nan

In [8]:
np.std(data)

nan

In [9]:
np.var(data)

nan

In [18]:
data_without_nan2 =  np.genfromtxt("Zadanie_1.csv", delimiter=';', skip_header=1)
np.shape(data_without_nan2)

(60, 16)

In [11]:
data_without_nan = data[~np.isnan(data)]

data_without_nan



array([3.600000e+01, 2.700000e+01, 7.100000e+01, 8.100000e+00,
       3.340000e+00, 1.140000e+01, 8.150000e+01, 3.243000e+03,
       8.800000e+00, 4.260000e+01, 1.170000e+01, 2.100000e+01,
       5.900000e+01, 5.900000e+01, 9.218700e+02, 3.500000e+01,
       2.300000e+01, 7.200000e+01, 1.110000e+01, 3.140000e+00,
       1.100000e+01, 7.880000e+01, 4.281000e+03, 3.600000e+00,
       5.070000e+01, 1.440000e+01, 8.000000e+00, 1.000000e+01,
       3.900000e+01, 5.700000e+01, 9.978750e+02, 4.400000e+01,
       2.900000e+01, 7.400000e+01, 1.040000e+01, 3.210000e+00,
       9.800000e+00, 8.160000e+01, 4.260000e+03, 8.000000e-01,
       3.940000e+01, 6.000000e+00, 6.000000e+00, 3.300000e+01,
       5.400000e+01, 9.623540e+02, 4.700000e+01, 4.500000e+01,
       7.900000e+01, 6.500000e+00, 3.410000e+00, 1.110000e+01,
       7.750000e+01, 3.125000e+03, 2.710000e+01, 5.020000e+01,
       2.060000e+01, 1.800000e+01, 8.000000e+00, 2.400000e+01,
       5.600000e+01, 9.822910e+02, 4.300000e+01, 3.5000

In [12]:
np.shape(data_without_nan)
np.isnan(data)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, Fals

In [13]:
#Zadanie 1d
np.nanmean(data)

338.2209319148936

In [14]:
np.nanstd(data)

1018.0734716093722

In [15]:
np.nanvar(data)

1036473.5935947591