In [27]:
import pandas as pd
import numpy as np

A =  np.genfromtxt("Zadanie_3_macierz_A.csv", delimiter=',')
B =  np.genfromtxt("Zadanie_3_macierz_B.csv", delimiter=',')
A

array([[2., 2., 3.],
       [1., 0., 4.],
       [6., 9., 7.]])

In [28]:
B

array([[ 1.,  5.,  2.],
       [ 6.,  6.,  4.],
       [ 1., 10.,  7.],
       [ 5.,  8.,  2.],
       [ 3.,  0.,  6.]])

In [29]:
np.dot(A,B.T)

array([[ 18.,  36.,  43.,  32.,  24.],
       [  9.,  22.,  29.,  13.,  27.],
       [ 65., 118., 145., 116.,  60.]])

In [30]:
np.dot(A[1],B[2])

29.0

In [31]:
A.shape

(3, 3)

In [32]:
B.shape

(5, 3)

In [39]:
C = np.zeros((A.shape[0],B.shape[0]))
for i in range(A.shape[0]):
    lengths_of_vector_A = np.linalg.norm(A[i])
    for j in range(B.shape[0]):
        lengths_of_vector_B = np.linalg.norm(B[j])
        C[i][j] = (np.dot(A[i],B[j]))/(lengths_of_vector_A*lengths_of_vector_B)

C

array([[0.7970534 , 0.93075784, 0.85152689, 0.80479273, 0.86772183],
       [0.3985267 , 0.56879646, 0.57428557, 0.32694705, 0.97618706],
       [0.92108283, 0.9763075 , 0.91890016, 0.9336035 , 0.69421013]])